#!/bin/bash

PID_FILE="/var/run/my_process.pid"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already running."
        exit 1
    fi
    nohup bash manage_my_process & echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    if [ ! -f "$PID_FILE" ]; then
        echo "manage_my_process is not running."
        exit 1
    fi
    kill "$(cat "$PID_FILE")"
    rm "$PID_FILE"
    echo "manage_my_process stopped"
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
