#!/usr/bin/env bash
# The init script manages another process. It can start, stop, or restart the process, and displays messages and creates/deletes a PID file.

PID_FILE="/var/run/my_process.pid"
 
if [ "$1" == "start" ]; then
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process started"
    else
        ./manage_my_process &
        echo "$!" > "$PID_FILE"
        echo "manage_my_process started"
    fi
elif [ "$1" == "stop" ]; then
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm "$PID_FILE"
        echo "manage_my_process stopped"
    
    fi
elif [ "$1" == "restart" ]; then
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm "$PID_FILE"
        echo "manage_my_process stopped"
    
    fi   
    ./manage_my_process &
    echo "$!" > "$PID_FILE"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
